# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorersource',
            name='batch',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
