# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0002_explorersource_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explorersource',
            old_name='source',
            new_name='query',
        ),
        migrations.RemoveField(
            model_name='explorersource',
            name='batch',
        ),
    ]
