# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0001_initial'),
        ('brunch', '0004_auto_20170703_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.IntervalSchedule'),
        ),
    ]
