# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:55
from __future__ import unicode_literals

import brunch.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brunch', '0006_auto_20170703_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunch_config_created', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brunch_config_last_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(brunch.models.AbstractBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brunch.Config')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.RemoveField(
            model_name='databaseconfig',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='databaseconfig',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='databaseconfig',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='databaseconfig',
            name='id',
        ),
        migrations.RemoveField(
            model_name='databaseconfig',
            name='modified_on',
        ),
        migrations.AddField(
            model_name='databaseconfig',
            name='config_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brunch.Config'),
            preserve_default=False,
        ),
    ]
