# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0007_auto_20170703_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconfig',
            name='active',
        ),
        migrations.RemoveField(
            model_name='databaseconfig',
            name='schedule',
        ),
    ]
