# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 09:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0008_auto_20170703_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('config_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brunch.Config')),
            ],
            options={
                'abstract': False,
            },
            bases=('brunch.config',),
        ),
        migrations.CreateModel(
            name='TargetConfig',
            fields=[
                ('config_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brunch.Config')),
            ],
            options={
                'abstract': False,
            },
            bases=('brunch.config',),
        ),
        migrations.RemoveField(
            model_name='databaseconfig',
            name='config_ptr',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='config',
        ),
        migrations.AlterField(
            model_name='databasecolumnoption',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brunch.Config'),
        ),
        migrations.CreateModel(
            name='DatabaseSourceConfig',
            fields=[
                ('sourceconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brunch.SourceConfig')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('connection_name', models.CharField(choices=[(b'default', b'default'), (b'qa', b'qa'), (b'replica', b'replica'), (b'redshift', b'redshift')], max_length=50)),
                ('select', models.CharField(max_length=1024)),
                ('table', models.CharField(max_length=128)),
                ('where', models.CharField(blank=True, max_length=1024)),
                ('batch_size', models.IntegerField(default=10000)),
                ('incremental_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Column name(s) used in select', size=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('brunch.sourceconfig',),
        ),
        migrations.CreateModel(
            name='DatabaseTargetConfig',
            fields=[
                ('targetconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brunch.TargetConfig')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('connection_name', models.CharField(choices=[(b'default', b'default'), (b'qa', b'qa'), (b'replica', b'replica'), (b'redshift', b'redshift')], max_length=50)),
                ('table', models.CharField(max_length=128)),
                ('mode', models.CharField(choices=[(b'insert', 'insert'), (b'insert_direct', 'insert_direct'), (b'truncate_insert', 'truncate_insert'), (b'replace', 'replace'), (b'merge', 'merge')], max_length=50)),
                ('merge_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='If merge mode is selected, Column name(s) used in select', size=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('brunch.targetconfig',),
        ),
        migrations.DeleteModel(
            name='DatabaseConfig',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='source_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brunch.SourceConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='target_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brunch.TargetConfig'),
            preserve_default=False,
        ),
    ]
