# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0010_auto_20170703_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasesourceconfig',
            name='name',
        ),
        migrations.RemoveField(
            model_name='databasetargetconfig',
            name='name',
        ),
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='name', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
