# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('brunch', '0011_auto_20170703_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
