# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0012_config_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='content_type',
            new_name='_content_type',
        ),
    ]
