# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0013_auto_20170703_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesourceconfig',
            name='order_by',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
