# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0014_databasesourceconfig_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasecolumnoption',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_options', to='brunch.Config'),
        ),
    ]
