# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_auto_20160105_2052'),
        ('brunch', '0015_auto_20170704_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorerSourceConfig',
            fields=[
                ('sourceconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brunch.SourceConfig')),
                ('batch_size', models.IntegerField(default=10000)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='explorer.Query')),
            ],
            options={
                'abstract': False,
            },
            bases=('brunch.sourceconfig',),
        ),
    ]
