# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0016_explorersourceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
