# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0019_filesourceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='databasecolumnoption',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='databasecolumnoption',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
