# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:27
from __future__ import unicode_literals

import brunch.generator.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorer', '0005_auto_20160105_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(brunch.generator.models.AbstractBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='ExplorerSource',
            fields=[
                ('basesource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generator.BaseSource')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='explorer.Query')),
            ],
            options={
                'abstract': False,
            },
            bases=('generator.basesource',),
        ),
        migrations.AddField(
            model_name='basesource',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generator_basesource_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basesource',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generator_basesource_last_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
