# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embulk', '0003_auto_20170703_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnoption',
            name='config',
        ),
        migrations.AddField(
            model_name='config',
            name='batch_size',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='config',
            name='column_options',
            field=models.ManyToManyField(blank=True, related_name='column_option_for_configs', to='embulk.ColumnOption'),
        ),
        migrations.AddField(
            model_name='config',
            name='connection_name',
            field=models.CharField(choices=[(b'default', b'default'), (b'qa', b'qa'), (b'replica', b'replica'), (b'redshift', b'redshift')], default='qa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='default_column_options',
            field=models.ManyToManyField(blank=True, related_name='default_column_option_for_configs', to='embulk.ColumnOption'),
        ),
        migrations.AddField(
            model_name='config',
            name='incremental_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, help_text='Column name used in select', size=None),
        ),
        migrations.AddField(
            model_name='config',
            name='select',
            field=models.CharField(default='*', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='table',
            field=models.CharField(default='core_event', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='where',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='columnoption',
            name='name',
            field=models.CharField(help_text='Column name used in select', max_length=255),
        ),
        migrations.AlterField(
            model_name='columnoption',
            name='timestamp_format',
            field=models.CharField(blank=True, help_text='default : %Y-%m-%d for date, %H:%M:%S for time, %Y-%m-%d %H:%M:%S for timestamp', max_length=50),
        ),
        migrations.AlterField(
            model_name='columnoption',
            name='type',
            field=models.CharField(blank=True, choices=[(b'boolean', 'boolean'), (b'long', 'long'), (b'double', 'double'), (b'string', 'string'), (b'json', 'json'), (b'timestamp', 'timestamp')], max_length=50, verbose_name='Convert to'),
        ),
        migrations.AlterField(
            model_name='columnoption',
            name='value_type',
            field=models.CharField(blank=True, choices=[(b'long', 'long'), (b'double', 'double'), (b'float', 'float'), (b'decimal', 'decimal'), (b'boolean', 'boolean'), (b'string', 'string'), (b'json', 'json'), (b'date', 'date'), (b'time', 'time'), (b'timestamp', 'timestamp')], max_length=50, verbose_name='Cast as'),
        ),
    ]
